version: '2'
services:
  nginx:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/nginx:${version}
    environment:
      - constraint:node==/.*(${ACCOUNT_ID}).*/

    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${APP_PORT}:80"
    networks:
      - i2b2-net
    depends_on:
      - i2b2transmartapp
      - irct
      - i2b2-wildfly

  # this will be deployed outside of i2b2transmart
  # stores 2 key encrypted Vault tokens between Jenkins and project
  redoctober.local:
    image: dqminh/redoctober:latest
    ports:
      - 8080:8080
    environment:
      RO_COMMONNAME: redoctober.local
    volumes:
      - redoctober:/var/lib/redoctober/data
    networks:
      - i2b2-net

  # PAL server
  pald:
    build:
      context: PAL/
      dockerfile: Dockerfile.server
    image: dtr.avl.dbmi.hms.harvard.edu/ar369/palserver:latest
    pid: host
    volumes:
      - redoctober:/var/lib/redoctober/data
      - pald:/var/run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redoctober.local
    networks:
      - i2b2-net

  # PAL client
  i2b2transmartapp:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/i2b2transmart-app:${version}
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    restart: always
    networks:
      - i2b2-net
    expose:
      - 8080
    mem_limit: "2g"
    entrypoint:
      - /docker-entrypoint
      - --ro_host=redoctober.local
      - --ro_port=8080
      - --
    command:
      - /usr/bin/pal
      - -socket=/var/run/pald.sock
      - -env=dev
      - --
      - env
      #- ./bin/catalina.sh
      #- run
    volumes:
      # pre-populate script
      - ./script/pal-integration:/docker-entrypoint
      # client
      - ./bin/pal:/usr/bin/pal
      #- ./bin/palpgpenc:/usr/bin/palpgpenc
      #- ./testdata/pubring.gpg:/etc/pal/pubring.gpg
      - redoctober:/var/lib/redoctober/data
      # server socket
      - pald:/var/run
    depends_on:
      - redoctober.local
      - pald
  i2b2-wildfly:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/i2b2-wildfly:${version}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CRC_BOOTSTRAP_PASSWORD=${CRC_BOOTSTRAP_PASSWORD}
      - CRC_DEMO_PASSWORD=${CRC_DEMO_PASSWORD}
      - ONT_BOOTSTRAP_PASSWORD=${ONT_BOOTSTRAP_PASSWORD}
      - ONT_DEMO_PASSWORD=${ONT_DEMO_PASSWORD}
      - PM_BOOTSTRAP_PASSWORD=${PM_BOOTSTRAP_PASSWORD}
      - WORK_BOOTSTRAP_PASSWORD=${WORK_BOOTSTRAP_PASSWORD}
      - WORK_DEMO_PASSWORD=${WORK_DEMO_PASSWORD}
    restart: always
    networks:
      - i2b2-net
    expose:
      - 9090
  irct:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct:${version}
    depends_on:
       - mysql
    environment:
      - IRCT_DB_CONNECTION_URL=mysql:3306/irct
      - IRCT_DB_CONNECTION_USER=root
      - IRCT_DB_CONNECTION_PASSWORD=${IRCT_DB_CONNECTION_PASSWORD}
      - IRCT_AUTH0_DOMAIN=${IRCT_AUTH0_DOMAIN}
      - IRCT_AUTH0_CLIENT_ID=${IRCT_AUTH0_CLIENT_ID}
      - IRCT_AUTH0_CLIENT_SECRET=${IRCT_AUTH0_CLIENT_SECRET}
    restart: always
    networks:
      - i2b2-net
    expose:
      - 8080
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${IRCT_DB_CONNECTION_PASSWORD}
      - MYSQL_DATABASE=irct
    restart: always
    expose:
      - 3306
    networks:
      - i2b2-net
  irct-init:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct-init:${version}
    depends_on:
      - mysql
      - irct
    environment:
      - IRCT_RESOURCE_NAME=${IRCT_RESOURCE_NAME}
      - IRCT_DB_CONNECTION_HOST=mysql
      - IRCT_DB_CONNECTION_USER=root
      - IRCT_DB_CONNECTION_PASSWORD=${IRCT_DB_CONNECTION_PASSWORD}
      - IRCT_AUTH0_DOMAIN=${IRCT_AUTH0_DOMAIN}
      - IRCT_AUTH0_CLIENT_ID=${IRCT_AUTH0_CLIENT_ID}
    restart: on-failure:10
    networks:
      - i2b2-net

volumes:
  redoctober:
  pald:

networks:
  i2b2-net:
