version: '2'
services:

  # nginx
  nginx:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/nginx:186.master
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=${ACCOUNT_ID}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - i2b2-net
    depends_on:
      # services
      - i2b2transmart
      - rserve

  ## i2b2transmart stack ##
  # i2b2transmart
  i2b2transmart:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/transmart:release-16.2
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=${ACCOUNT_ID}"
    environment:
      - ORACLEHOST=transmartdb
      - DB_PORT=1521
      - DB_USER=biomart_user
      - BIOMART_USER=biomart_user
      - RSERVE_HOST=rserve
      - RSERVE_PORT=6311
    restart: always
    depends_on:
      - oracledb
    networks:
      - i2b2-net
    expose:
      - 8080

  # Rserve
  rserve:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/rserve:197.nhanes-dev
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=${ACCOUNT_ID}"
    restart: always
    expose:
      - 6311
    networks:
      - i2b2-net

  # local running Oracle DB
  oracledb:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/oracle:release-16.2
    hostname: transmartdb
    container_name: transmartdb
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=${ACCOUNT_ID}"
    restart: always
    expose:
      - 1521
    networks:
      - i2b2-net


networks:
    i2b2-net:
#        internal: true
